// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: exchange.proto

package exchange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	MatchingEngine_SubmitOrder_FullMethodName       = "/exchange.MatchingEngine/SubmitOrder"
	MatchingEngine_CancelOrder_FullMethodName       = "/exchange.MatchingEngine/CancelOrder"
	MatchingEngine_StreamTrades_FullMethodName      = "/exchange.MatchingEngine/StreamTrades"
	MatchingEngine_StreamBookUpdates_FullMethodName = "/exchange.MatchingEngine/StreamBookUpdates"
)

// MatchingEngineClient is the client API for MatchingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingEngineClient interface {
	SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	StreamTrades(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MatchingEngine_StreamTradesClient, error)
	StreamBookUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MatchingEngine_StreamBookUpdatesClient, error)
}

type matchingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineClient(cc grpc.ClientConnInterface) MatchingEngineClient {
	return &matchingEngineClient{cc}
}

func (c *matchingEngineClient) SubmitOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, MatchingEngine_SubmitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) CancelOrder(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, MatchingEngine_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchingEngineClient) StreamTrades(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MatchingEngine_StreamTradesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchingEngine_ServiceDesc.Streams[0], MatchingEngine_StreamTrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &matchingEngineStreamTradesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatchingEngine_StreamTradesClient interface {
	Recv() (*Trade, error)
	grpc.ClientStream
}

type matchingEngineStreamTradesClient struct {
	grpc.ClientStream
}

func (x *matchingEngineStreamTradesClient) Recv() (*Trade, error) {
	m := new(Trade)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *matchingEngineClient) StreamBookUpdates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (MatchingEngine_StreamBookUpdatesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchingEngine_ServiceDesc.Streams[1], MatchingEngine_StreamBookUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &matchingEngineStreamBookUpdatesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatchingEngine_StreamBookUpdatesClient interface {
	Recv() (*BookSnapshot, error)
	grpc.ClientStream
}

type matchingEngineStreamBookUpdatesClient struct {
	grpc.ClientStream
}

func (x *matchingEngineStreamBookUpdatesClient) Recv() (*BookSnapshot, error) {
	m := new(BookSnapshot)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MatchingEngineServer is the server API for MatchingEngine service.
// All implementations must embed UnimplementedMatchingEngineServer
// for forward compatibility
type MatchingEngineServer interface {
	SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error)
	CancelOrder(context.Context, *CancelRequest) (*CancelResponse, error)
	StreamTrades(*Empty, MatchingEngine_StreamTradesServer) error
	StreamBookUpdates(*Empty, MatchingEngine_StreamBookUpdatesServer) error
	mustEmbedUnimplementedMatchingEngineServer()
}

// UnimplementedMatchingEngineServer must be embedded to have forward compatible implementations.
type UnimplementedMatchingEngineServer struct {
}

func (UnimplementedMatchingEngineServer) SubmitOrder(context.Context, *OrderRequest) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (UnimplementedMatchingEngineServer) CancelOrder(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatchingEngineServer) StreamTrades(*Empty, MatchingEngine_StreamTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTrades not implemented")
}
func (UnimplementedMatchingEngineServer) StreamBookUpdates(*Empty, MatchingEngine_StreamBookUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBookUpdates not implemented")
}
func (UnimplementedMatchingEngineServer) mustEmbedUnimplementedMatchingEngineServer() {}

// UnsafeMatchingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServer will
// result in compilation errors.
type UnsafeMatchingEngineServer interface {
	mustEmbedUnimplementedMatchingEngineServer()
}

func RegisterMatchingEngineServer(s grpc.ServiceRegistrar, srv MatchingEngineServer) {
	s.RegisterService(&MatchingEngine_ServiceDesc, srv)
}

func _MatchingEngine_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_SubmitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).SubmitOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngine_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServer).CancelOrder(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchingEngine_StreamTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchingEngineServer).StreamTrades(m, &matchingEngineStreamTradesServer{ServerStream: stream})
}

type MatchingEngine_StreamTradesServer interface {
	Send(*Trade) error
	grpc.ServerStream
}

type matchingEngineStreamTradesServer struct {
	grpc.ServerStream
}

func (x *matchingEngineStreamTradesServer) Send(m *Trade) error {
	return x.ServerStream.SendMsg(m)
}

func _MatchingEngine_StreamBookUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchingEngineServer).StreamBookUpdates(m, &matchingEngineStreamBookUpdatesServer{ServerStream: stream})
}

type MatchingEngine_StreamBookUpdatesServer interface {
	Send(*BookSnapshot) error
	grpc.ServerStream
}

type matchingEngineStreamBookUpdatesServer struct {
	grpc.ServerStream
}

func (x *matchingEngineStreamBookUpdatesServer) Send(m *BookSnapshot) error {
	return x.ServerStream.SendMsg(m)
}

// MatchingEngine_ServiceDesc is the grpc.ServiceDesc for MatchingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.MatchingEngine",
	HandlerType: (*MatchingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrder",
			Handler:    _MatchingEngine_SubmitOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatchingEngine_CancelOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTrades",
			Handler:       _MatchingEngine_StreamTrades_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamBookUpdates",
			Handler:       _MatchingEngine_StreamBookUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "exchange.proto",
}
