FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates protobuf-compiler protobuf-compiler-grpc golang-go
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.1
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.4.0
ENV PATH=$PATH:/root/go/bin
WORKDIR /workspace
CMD protoc -I=proto \
    --go_out=backend/internal/grpcclient --go_opt=paths=source_relative \
    --go-grpc_out=backend/internal/grpcclient --go-grpc_opt=paths=source_relative \
    --cpp_out=engine/include \
    --grpc_out=engine/include --plugin=protoc-gen-grpc=/usr/bin/grpc_cpp_plugin \
    proto/exchange.proto
