// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: exchange.proto
#ifndef GRPC_exchange_2eproto__INCLUDED
#define GRPC_exchange_2eproto__INCLUDED

#include "exchange.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace exchange {

class MatchingEngine final {
 public:
  static constexpr char const* service_full_name() {
    return "exchange.MatchingEngine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::exchange::OrderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>> AsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>>(AsyncSubmitOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>> PrepareAsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>>(PrepareAsyncSubmitOrderRaw(context, request, cq));
    }
    virtual ::grpc::Status CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::exchange::CancelResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>> AsyncCancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>>(AsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>> PrepareAsyncCancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>>(PrepareAsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::Trade>> StreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::Trade>>(StreamTradesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>> AsyncStreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>>(AsyncStreamTradesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>> PrepareAsyncStreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>>(PrepareAsyncStreamTradesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::BookSnapshot>> StreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::exchange::BookSnapshot>>(StreamBookUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>> AsyncStreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>>(AsyncStreamBookUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>> PrepareAsyncStreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>>(PrepareAsyncStreamBookUpdatesRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamTrades(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::ClientReadReactor< ::exchange::Trade>* reactor) = 0;
      #else
      virtual void StreamTrades(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::Trade>* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void StreamBookUpdates(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::ClientReadReactor< ::exchange::BookSnapshot>* reactor) = 0;
      #else
      virtual void StreamBookUpdates(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::BookSnapshot>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>* AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::OrderResponse>* PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>* AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::exchange::CancelResponse>* PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::exchange::Trade>* StreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>* AsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::Trade>* PrepareAsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::exchange::BookSnapshot>* StreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>* AsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::exchange::BookSnapshot>* PrepareAsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::exchange::OrderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>> AsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>>(AsyncSubmitOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>> PrepareAsyncSubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>>(PrepareAsyncSubmitOrderRaw(context, request, cq));
    }
    ::grpc::Status CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::exchange::CancelResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>> AsyncCancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>>(AsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>> PrepareAsyncCancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>>(PrepareAsyncCancelOrderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::exchange::Trade>> StreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::exchange::Trade>>(StreamTradesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::Trade>> AsyncStreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::Trade>>(AsyncStreamTradesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::Trade>> PrepareAsyncStreamTrades(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::Trade>>(PrepareAsyncStreamTradesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::exchange::BookSnapshot>> StreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::exchange::BookSnapshot>>(StreamBookUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>> AsyncStreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>>(AsyncStreamBookUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>> PrepareAsyncStreamBookUpdates(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>>(PrepareAsyncStreamBookUpdatesRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) override;
      void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) override;
      void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamTrades(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::ClientReadReactor< ::exchange::Trade>* reactor) override;
      #else
      void StreamTrades(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::Trade>* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void StreamBookUpdates(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::ClientReadReactor< ::exchange::BookSnapshot>* reactor) override;
      #else
      void StreamBookUpdates(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::BookSnapshot>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::exchange::Trade>* StreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) override;
    ::grpc::ClientAsyncReader< ::exchange::Trade>* AsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::exchange::Trade>* PrepareAsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::exchange::BookSnapshot>* StreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) override;
    ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>* AsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::exchange::BookSnapshot>* PrepareAsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_CancelOrder_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamTrades_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamBookUpdates_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitOrder(::grpc::ServerContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response);
    virtual ::grpc::Status CancelOrder(::grpc::ServerContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response);
    virtual ::grpc::Status StreamTrades(::grpc::ServerContext* context, const ::exchange::Empty* request, ::grpc::ServerWriter< ::exchange::Trade>* writer);
    virtual ::grpc::Status StreamBookUpdates(::grpc::ServerContext* context, const ::exchange::Empty* request, ::grpc::ServerWriter< ::exchange::BookSnapshot>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitOrder(::grpc::ServerContext* context, ::exchange::OrderRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchange::OrderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CancelOrder() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelOrder(::grpc::ServerContext* context, ::exchange::CancelRequest* request, ::grpc::ServerAsyncResponseWriter< ::exchange::CancelResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamTrades() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamTrades(::grpc::ServerContext* context, ::exchange::Empty* request, ::grpc::ServerAsyncWriter< ::exchange::Trade>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamBookUpdates() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamBookUpdates(::grpc::ServerContext* context, ::exchange::Empty* request, ::grpc::ServerAsyncWriter< ::exchange::BookSnapshot>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitOrder<WithAsyncMethod_CancelOrder<WithAsyncMethod_StreamTrades<WithAsyncMethod_StreamBookUpdates<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SubmitOrder() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::exchange::OrderRequest, ::exchange::OrderResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response) { return this->SubmitOrder(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitOrder(
        ::grpc::experimental::MessageAllocator< ::exchange::OrderRequest, ::exchange::OrderResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::exchange::OrderRequest, ::exchange::OrderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SubmitOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SubmitOrder(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CancelOrder() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::exchange::CancelRequest, ::exchange::CancelResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response) { return this->CancelOrder(context, request, response); }));}
    void SetMessageAllocatorFor_CancelOrder(
        ::grpc::experimental::MessageAllocator< ::exchange::CancelRequest, ::exchange::CancelResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::exchange::CancelRequest, ::exchange::CancelResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CancelOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CancelOrder(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamTrades() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::exchange::Empty, ::exchange::Trade>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::exchange::Empty* request) { return this->StreamTrades(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::exchange::Trade>* StreamTrades(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::Empty* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::exchange::Trade>* StreamTrades(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::exchange::Empty* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_StreamBookUpdates() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::exchange::Empty, ::exchange::BookSnapshot>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::exchange::Empty* request) { return this->StreamBookUpdates(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::exchange::BookSnapshot>* StreamBookUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::exchange::Empty* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::exchange::BookSnapshot>* StreamBookUpdates(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::exchange::Empty* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SubmitOrder<ExperimentalWithCallbackMethod_CancelOrder<ExperimentalWithCallbackMethod_StreamTrades<ExperimentalWithCallbackMethod_StreamBookUpdates<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SubmitOrder<ExperimentalWithCallbackMethod_CancelOrder<ExperimentalWithCallbackMethod_StreamTrades<ExperimentalWithCallbackMethod_StreamBookUpdates<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CancelOrder() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamTrades() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamBookUpdates() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CancelOrder() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCancelOrder(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamTrades() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamTrades(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(2, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamBookUpdates() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamBookUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SubmitOrder() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitOrder(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SubmitOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SubmitOrder(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CancelOrder() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CancelOrder(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CancelOrder(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CancelOrder(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamTrades() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->StreamTrades(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamTrades(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* StreamTrades(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_StreamBookUpdates() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->StreamBookUpdates(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamBookUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* StreamBookUpdates(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitOrder() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::OrderRequest, ::exchange::OrderResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::exchange::OrderRequest, ::exchange::OrderResponse>* streamer) {
                       return this->StreamedSubmitOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitOrder(::grpc::ServerContext* /*context*/, const ::exchange::OrderRequest* /*request*/, ::exchange::OrderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::OrderRequest,::exchange::OrderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CancelOrder : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CancelOrder() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::exchange::CancelRequest, ::exchange::CancelResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::exchange::CancelRequest, ::exchange::CancelResponse>* streamer) {
                       return this->StreamedCancelOrder(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CancelOrder() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CancelOrder(::grpc::ServerContext* /*context*/, const ::exchange::CancelRequest* /*request*/, ::exchange::CancelResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCancelOrder(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::exchange::CancelRequest,::exchange::CancelResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitOrder<WithStreamedUnaryMethod_CancelOrder<Service > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamTrades : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamTrades() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::exchange::Empty, ::exchange::Trade>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::exchange::Empty, ::exchange::Trade>* streamer) {
                       return this->StreamedStreamTrades(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamTrades() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamTrades(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::Trade>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamTrades(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::exchange::Empty,::exchange::Trade>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamBookUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamBookUpdates() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::exchange::Empty, ::exchange::BookSnapshot>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerSplitStreamer<
                     ::exchange::Empty, ::exchange::BookSnapshot>* streamer) {
                       return this->StreamedStreamBookUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamBookUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamBookUpdates(::grpc::ServerContext* /*context*/, const ::exchange::Empty* /*request*/, ::grpc::ServerWriter< ::exchange::BookSnapshot>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamBookUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::exchange::Empty,::exchange::BookSnapshot>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamTrades<WithSplitStreamingMethod_StreamBookUpdates<Service > > SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitOrder<WithStreamedUnaryMethod_CancelOrder<WithSplitStreamingMethod_StreamTrades<WithSplitStreamingMethod_StreamBookUpdates<Service > > > > StreamedService;
};

}  // namespace exchange


#endif  // GRPC_exchange_2eproto__INCLUDED
