// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: exchange.proto

#include "exchange.pb.h"
#include "exchange.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace exchange {

static const char* MatchingEngine_method_names[] = {
  "/exchange.MatchingEngine/SubmitOrder",
  "/exchange.MatchingEngine/CancelOrder",
  "/exchange.MatchingEngine/StreamTrades",
  "/exchange.MatchingEngine/StreamBookUpdates",
};

std::unique_ptr< MatchingEngine::Stub> MatchingEngine::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MatchingEngine::Stub> stub(new MatchingEngine::Stub(channel));
  return stub;
}

MatchingEngine::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SubmitOrder_(MatchingEngine_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CancelOrder_(MatchingEngine_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamTrades_(MatchingEngine_method_names[2], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_StreamBookUpdates_(MatchingEngine_method_names[3], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status MatchingEngine::Stub::SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::exchange::OrderResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SubmitOrder_, context, request, response);
}

void MatchingEngine::Stub::experimental_async::SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, std::move(f));
}

void MatchingEngine::Stub::experimental_async::SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, std::move(f));
}

void MatchingEngine::Stub::experimental_async::SubmitOrder(::grpc::ClientContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, reactor);
}

void MatchingEngine::Stub::experimental_async::SubmitOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::OrderResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SubmitOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* MatchingEngine::Stub::AsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::exchange::OrderResponse>::Create(channel_.get(), cq, rpcmethod_SubmitOrder_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::exchange::OrderResponse>* MatchingEngine::Stub::PrepareAsyncSubmitOrderRaw(::grpc::ClientContext* context, const ::exchange::OrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::exchange::OrderResponse>::Create(channel_.get(), cq, rpcmethod_SubmitOrder_, context, request, false);
}

::grpc::Status MatchingEngine::Stub::CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::exchange::CancelResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_CancelOrder_, context, request, response);
}

void MatchingEngine::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void MatchingEngine::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, std::move(f));
}

void MatchingEngine::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

void MatchingEngine::Stub::experimental_async::CancelOrder(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::exchange::CancelResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_CancelOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* MatchingEngine::Stub::AsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::exchange::CancelResponse>::Create(channel_.get(), cq, rpcmethod_CancelOrder_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::exchange::CancelResponse>* MatchingEngine::Stub::PrepareAsyncCancelOrderRaw(::grpc::ClientContext* context, const ::exchange::CancelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::exchange::CancelResponse>::Create(channel_.get(), cq, rpcmethod_CancelOrder_, context, request, false);
}

::grpc::ClientReader< ::exchange::Trade>* MatchingEngine::Stub::StreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::exchange::Trade>::Create(channel_.get(), rpcmethod_StreamTrades_, context, request);
}

void MatchingEngine::Stub::experimental_async::StreamTrades(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::Trade>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::exchange::Trade>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamTrades_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::exchange::Trade>* MatchingEngine::Stub::AsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::exchange::Trade>::Create(channel_.get(), cq, rpcmethod_StreamTrades_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::exchange::Trade>* MatchingEngine::Stub::PrepareAsyncStreamTradesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::exchange::Trade>::Create(channel_.get(), cq, rpcmethod_StreamTrades_, context, request, false, nullptr);
}

::grpc::ClientReader< ::exchange::BookSnapshot>* MatchingEngine::Stub::StreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::exchange::BookSnapshot>::Create(channel_.get(), rpcmethod_StreamBookUpdates_, context, request);
}

void MatchingEngine::Stub::experimental_async::StreamBookUpdates(::grpc::ClientContext* context, ::exchange::Empty* request, ::grpc::experimental::ClientReadReactor< ::exchange::BookSnapshot>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::exchange::BookSnapshot>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamBookUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::exchange::BookSnapshot>* MatchingEngine::Stub::AsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::exchange::BookSnapshot>::Create(channel_.get(), cq, rpcmethod_StreamBookUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::exchange::BookSnapshot>* MatchingEngine::Stub::PrepareAsyncStreamBookUpdatesRaw(::grpc::ClientContext* context, const ::exchange::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::exchange::BookSnapshot>::Create(channel_.get(), cq, rpcmethod_StreamBookUpdates_, context, request, false, nullptr);
}

MatchingEngine::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchingEngine_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchingEngine::Service, ::exchange::OrderRequest, ::exchange::OrderResponse>(
          [](MatchingEngine::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::exchange::OrderRequest* req,
             ::exchange::OrderResponse* resp) {
               return service->SubmitOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchingEngine_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MatchingEngine::Service, ::exchange::CancelRequest, ::exchange::CancelResponse>(
          [](MatchingEngine::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::exchange::CancelRequest* req,
             ::exchange::CancelResponse* resp) {
               return service->CancelOrder(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchingEngine_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MatchingEngine::Service, ::exchange::Empty, ::exchange::Trade>(
          [](MatchingEngine::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::exchange::Empty* req,
             ::grpc_impl::ServerWriter<::exchange::Trade>* writer) {
               return service->StreamTrades(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MatchingEngine_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MatchingEngine::Service, ::exchange::Empty, ::exchange::BookSnapshot>(
          [](MatchingEngine::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::exchange::Empty* req,
             ::grpc_impl::ServerWriter<::exchange::BookSnapshot>* writer) {
               return service->StreamBookUpdates(ctx, req, writer);
             }, this)));
}

MatchingEngine::Service::~Service() {
}

::grpc::Status MatchingEngine::Service::SubmitOrder(::grpc::ServerContext* context, const ::exchange::OrderRequest* request, ::exchange::OrderResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchingEngine::Service::CancelOrder(::grpc::ServerContext* context, const ::exchange::CancelRequest* request, ::exchange::CancelResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchingEngine::Service::StreamTrades(::grpc::ServerContext* context, const ::exchange::Empty* request, ::grpc::ServerWriter< ::exchange::Trade>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MatchingEngine::Service::StreamBookUpdates(::grpc::ServerContext* context, const ::exchange::Empty* request, ::grpc::ServerWriter< ::exchange::BookSnapshot>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace exchange

