// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchange.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_exchange_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_exchange_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_exchange_2eproto;
namespace exchange {
class BookLevel;
class BookLevelDefaultTypeInternal;
extern BookLevelDefaultTypeInternal _BookLevel_default_instance_;
class BookSnapshot;
class BookSnapshotDefaultTypeInternal;
extern BookSnapshotDefaultTypeInternal _BookSnapshot_default_instance_;
class CancelRequest;
class CancelRequestDefaultTypeInternal;
extern CancelRequestDefaultTypeInternal _CancelRequest_default_instance_;
class CancelResponse;
class CancelResponseDefaultTypeInternal;
extern CancelResponseDefaultTypeInternal _CancelResponse_default_instance_;
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class OrderRequest;
class OrderRequestDefaultTypeInternal;
extern OrderRequestDefaultTypeInternal _OrderRequest_default_instance_;
class OrderResponse;
class OrderResponseDefaultTypeInternal;
extern OrderResponseDefaultTypeInternal _OrderResponse_default_instance_;
class Trade;
class TradeDefaultTypeInternal;
extern TradeDefaultTypeInternal _Trade_default_instance_;
}  // namespace exchange
PROTOBUF_NAMESPACE_OPEN
template<> ::exchange::BookLevel* Arena::CreateMaybeMessage<::exchange::BookLevel>(Arena*);
template<> ::exchange::BookSnapshot* Arena::CreateMaybeMessage<::exchange::BookSnapshot>(Arena*);
template<> ::exchange::CancelRequest* Arena::CreateMaybeMessage<::exchange::CancelRequest>(Arena*);
template<> ::exchange::CancelResponse* Arena::CreateMaybeMessage<::exchange::CancelResponse>(Arena*);
template<> ::exchange::Empty* Arena::CreateMaybeMessage<::exchange::Empty>(Arena*);
template<> ::exchange::OrderRequest* Arena::CreateMaybeMessage<::exchange::OrderRequest>(Arena*);
template<> ::exchange::OrderResponse* Arena::CreateMaybeMessage<::exchange::OrderResponse>(Arena*);
template<> ::exchange::Trade* Arena::CreateMaybeMessage<::exchange::Trade>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace exchange {

enum Side : int {
  BUY = 0,
  SELL = 1,
  Side_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Side_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Side_IsValid(int value);
constexpr Side Side_MIN = BUY;
constexpr Side Side_MAX = SELL;
constexpr int Side_ARRAYSIZE = Side_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Side_descriptor();
template<typename T>
inline const std::string& Side_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Side>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Side_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Side_descriptor(), enum_t_value);
}
inline bool Side_Parse(
    const std::string& name, Side* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Side>(
    Side_descriptor(), name, value);
}
// ===================================================================

class OrderRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.OrderRequest) */ {
 public:
  inline OrderRequest() : OrderRequest(nullptr) {};
  virtual ~OrderRequest();

  OrderRequest(const OrderRequest& from);
  OrderRequest(OrderRequest&& from) noexcept
    : OrderRequest() {
    *this = ::std::move(from);
  }

  inline OrderRequest& operator=(const OrderRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderRequest& operator=(OrderRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OrderRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OrderRequest* internal_default_instance() {
    return reinterpret_cast<const OrderRequest*>(
               &_OrderRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OrderRequest& a, OrderRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OrderRequest* New() const final {
    return CreateMaybeMessage<OrderRequest>(nullptr);
  }

  OrderRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OrderRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OrderRequest& from);
  void MergeFrom(const OrderRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.OrderRequest";
  }
  protected:
  explicit OrderRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIdFieldNumber = 1,
    kPriceFieldNumber = 3,
    kQuantityFieldNumber = 4,
    kTimestampNsFieldNumber = 5,
    kSideFieldNumber = 2,
  };
  // string order_id = 1;
  void clear_order_id();
  const std::string& order_id() const;
  void set_order_id(const std::string& value);
  void set_order_id(std::string&& value);
  void set_order_id(const char* value);
  void set_order_id(const char* value, size_t size);
  std::string* mutable_order_id();
  std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_order_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_order_id(
      std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // double price = 3;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // int64 quantity = 4;
  void clear_quantity();
  ::PROTOBUF_NAMESPACE_ID::int64 quantity() const;
  void set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_quantity() const;
  void _internal_set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 timestamp_ns = 5;
  void clear_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns() const;
  void set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // .exchange.Side side = 2;
  void clear_side();
  ::exchange::Side side() const;
  void set_side(::exchange::Side value);
  private:
  ::exchange::Side _internal_side() const;
  void _internal_set_side(::exchange::Side value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.OrderRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
  double price_;
  ::PROTOBUF_NAMESPACE_ID::int64 quantity_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns_;
  int side_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class OrderResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.OrderResponse) */ {
 public:
  inline OrderResponse() : OrderResponse(nullptr) {};
  virtual ~OrderResponse();

  OrderResponse(const OrderResponse& from);
  OrderResponse(OrderResponse&& from) noexcept
    : OrderResponse() {
    *this = ::std::move(from);
  }

  inline OrderResponse& operator=(const OrderResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline OrderResponse& operator=(OrderResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OrderResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OrderResponse* internal_default_instance() {
    return reinterpret_cast<const OrderResponse*>(
               &_OrderResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OrderResponse& a, OrderResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(OrderResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OrderResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OrderResponse* New() const final {
    return CreateMaybeMessage<OrderResponse>(nullptr);
  }

  OrderResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OrderResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OrderResponse& from);
  void MergeFrom(const OrderResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OrderResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.OrderResponse";
  }
  protected:
  explicit OrderResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIdFieldNumber = 1,
    kMessageFieldNumber = 3,
    kAcceptedFieldNumber = 2,
  };
  // string order_id = 1;
  void clear_order_id();
  const std::string& order_id() const;
  void set_order_id(const std::string& value);
  void set_order_id(std::string&& value);
  void set_order_id(const char* value);
  void set_order_id(const char* value, size_t size);
  std::string* mutable_order_id();
  std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_order_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_order_id(
      std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // string message = 3;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool accepted = 2;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.OrderResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool accepted_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class CancelRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.CancelRequest) */ {
 public:
  inline CancelRequest() : CancelRequest(nullptr) {};
  virtual ~CancelRequest();

  CancelRequest(const CancelRequest& from);
  CancelRequest(CancelRequest&& from) noexcept
    : CancelRequest() {
    *this = ::std::move(from);
  }

  inline CancelRequest& operator=(const CancelRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CancelRequest& operator=(CancelRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CancelRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CancelRequest* internal_default_instance() {
    return reinterpret_cast<const CancelRequest*>(
               &_CancelRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CancelRequest& a, CancelRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(CancelRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CancelRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CancelRequest* New() const final {
    return CreateMaybeMessage<CancelRequest>(nullptr);
  }

  CancelRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CancelRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CancelRequest& from);
  void MergeFrom(const CancelRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CancelRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.CancelRequest";
  }
  protected:
  explicit CancelRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIdFieldNumber = 1,
  };
  // string order_id = 1;
  void clear_order_id();
  const std::string& order_id() const;
  void set_order_id(const std::string& value);
  void set_order_id(std::string&& value);
  void set_order_id(const char* value);
  void set_order_id(const char* value, size_t size);
  std::string* mutable_order_id();
  std::string* release_order_id();
  void set_allocated_order_id(std::string* order_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_order_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_order_id(
      std::string* order_id);
  private:
  const std::string& _internal_order_id() const;
  void _internal_set_order_id(const std::string& value);
  std::string* _internal_mutable_order_id();
  public:

  // @@protoc_insertion_point(class_scope:exchange.CancelRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr order_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class CancelResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.CancelResponse) */ {
 public:
  inline CancelResponse() : CancelResponse(nullptr) {};
  virtual ~CancelResponse();

  CancelResponse(const CancelResponse& from);
  CancelResponse(CancelResponse&& from) noexcept
    : CancelResponse() {
    *this = ::std::move(from);
  }

  inline CancelResponse& operator=(const CancelResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CancelResponse& operator=(CancelResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CancelResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CancelResponse* internal_default_instance() {
    return reinterpret_cast<const CancelResponse*>(
               &_CancelResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CancelResponse& a, CancelResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CancelResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CancelResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CancelResponse* New() const final {
    return CreateMaybeMessage<CancelResponse>(nullptr);
  }

  CancelResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CancelResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CancelResponse& from);
  void MergeFrom(const CancelResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CancelResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.CancelResponse";
  }
  protected:
  explicit CancelResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.CancelResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class Trade PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.Trade) */ {
 public:
  inline Trade() : Trade(nullptr) {};
  virtual ~Trade();

  Trade(const Trade& from);
  Trade(Trade&& from) noexcept
    : Trade() {
    *this = ::std::move(from);
  }

  inline Trade& operator=(const Trade& from) {
    CopyFrom(from);
    return *this;
  }
  inline Trade& operator=(Trade&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Trade& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Trade* internal_default_instance() {
    return reinterpret_cast<const Trade*>(
               &_Trade_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Trade& a, Trade& b) {
    a.Swap(&b);
  }
  inline void Swap(Trade* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Trade* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Trade* New() const final {
    return CreateMaybeMessage<Trade>(nullptr);
  }

  Trade* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Trade>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Trade& from);
  void MergeFrom(const Trade& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trade* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.Trade";
  }
  protected:
  explicit Trade(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTradeIdFieldNumber = 1,
    kBuyOrderIdFieldNumber = 2,
    kSellOrderIdFieldNumber = 3,
    kPriceFieldNumber = 4,
    kQuantityFieldNumber = 5,
    kTimestampNsFieldNumber = 6,
  };
  // string trade_id = 1;
  void clear_trade_id();
  const std::string& trade_id() const;
  void set_trade_id(const std::string& value);
  void set_trade_id(std::string&& value);
  void set_trade_id(const char* value);
  void set_trade_id(const char* value, size_t size);
  std::string* mutable_trade_id();
  std::string* release_trade_id();
  void set_allocated_trade_id(std::string* trade_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_trade_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_trade_id(
      std::string* trade_id);
  private:
  const std::string& _internal_trade_id() const;
  void _internal_set_trade_id(const std::string& value);
  std::string* _internal_mutable_trade_id();
  public:

  // string buy_order_id = 2;
  void clear_buy_order_id();
  const std::string& buy_order_id() const;
  void set_buy_order_id(const std::string& value);
  void set_buy_order_id(std::string&& value);
  void set_buy_order_id(const char* value);
  void set_buy_order_id(const char* value, size_t size);
  std::string* mutable_buy_order_id();
  std::string* release_buy_order_id();
  void set_allocated_buy_order_id(std::string* buy_order_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_buy_order_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_buy_order_id(
      std::string* buy_order_id);
  private:
  const std::string& _internal_buy_order_id() const;
  void _internal_set_buy_order_id(const std::string& value);
  std::string* _internal_mutable_buy_order_id();
  public:

  // string sell_order_id = 3;
  void clear_sell_order_id();
  const std::string& sell_order_id() const;
  void set_sell_order_id(const std::string& value);
  void set_sell_order_id(std::string&& value);
  void set_sell_order_id(const char* value);
  void set_sell_order_id(const char* value, size_t size);
  std::string* mutable_sell_order_id();
  std::string* release_sell_order_id();
  void set_allocated_sell_order_id(std::string* sell_order_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_sell_order_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_sell_order_id(
      std::string* sell_order_id);
  private:
  const std::string& _internal_sell_order_id() const;
  void _internal_set_sell_order_id(const std::string& value);
  std::string* _internal_mutable_sell_order_id();
  public:

  // double price = 4;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // int64 quantity = 5;
  void clear_quantity();
  ::PROTOBUF_NAMESPACE_ID::int64 quantity() const;
  void set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_quantity() const;
  void _internal_set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int64 timestamp_ns = 6;
  void clear_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns() const;
  void set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.Trade)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trade_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr buy_order_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sell_order_id_;
  double price_;
  ::PROTOBUF_NAMESPACE_ID::int64 quantity_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class BookLevel PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.BookLevel) */ {
 public:
  inline BookLevel() : BookLevel(nullptr) {};
  virtual ~BookLevel();

  BookLevel(const BookLevel& from);
  BookLevel(BookLevel&& from) noexcept
    : BookLevel() {
    *this = ::std::move(from);
  }

  inline BookLevel& operator=(const BookLevel& from) {
    CopyFrom(from);
    return *this;
  }
  inline BookLevel& operator=(BookLevel&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BookLevel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BookLevel* internal_default_instance() {
    return reinterpret_cast<const BookLevel*>(
               &_BookLevel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(BookLevel& a, BookLevel& b) {
    a.Swap(&b);
  }
  inline void Swap(BookLevel* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BookLevel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BookLevel* New() const final {
    return CreateMaybeMessage<BookLevel>(nullptr);
  }

  BookLevel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BookLevel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BookLevel& from);
  void MergeFrom(const BookLevel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BookLevel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.BookLevel";
  }
  protected:
  explicit BookLevel(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPriceFieldNumber = 1,
    kTotalQuantityFieldNumber = 2,
  };
  // double price = 1;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // int64 total_quantity = 2;
  void clear_total_quantity();
  ::PROTOBUF_NAMESPACE_ID::int64 total_quantity() const;
  void set_total_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_total_quantity() const;
  void _internal_set_total_quantity(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.BookLevel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  double price_;
  ::PROTOBUF_NAMESPACE_ID::int64 total_quantity_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class BookSnapshot PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.BookSnapshot) */ {
 public:
  inline BookSnapshot() : BookSnapshot(nullptr) {};
  virtual ~BookSnapshot();

  BookSnapshot(const BookSnapshot& from);
  BookSnapshot(BookSnapshot&& from) noexcept
    : BookSnapshot() {
    *this = ::std::move(from);
  }

  inline BookSnapshot& operator=(const BookSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline BookSnapshot& operator=(BookSnapshot&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BookSnapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BookSnapshot* internal_default_instance() {
    return reinterpret_cast<const BookSnapshot*>(
               &_BookSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(BookSnapshot& a, BookSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(BookSnapshot* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BookSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BookSnapshot* New() const final {
    return CreateMaybeMessage<BookSnapshot>(nullptr);
  }

  BookSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BookSnapshot>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BookSnapshot& from);
  void MergeFrom(const BookSnapshot& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BookSnapshot* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.BookSnapshot";
  }
  protected:
  explicit BookSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBidsFieldNumber = 1,
    kAsksFieldNumber = 2,
    kTimestampNsFieldNumber = 3,
  };
  // repeated .exchange.BookLevel bids = 1;
  int bids_size() const;
  private:
  int _internal_bids_size() const;
  public:
  void clear_bids();
  ::exchange::BookLevel* mutable_bids(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >*
      mutable_bids();
  private:
  const ::exchange::BookLevel& _internal_bids(int index) const;
  ::exchange::BookLevel* _internal_add_bids();
  public:
  const ::exchange::BookLevel& bids(int index) const;
  ::exchange::BookLevel* add_bids();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >&
      bids() const;

  // repeated .exchange.BookLevel asks = 2;
  int asks_size() const;
  private:
  int _internal_asks_size() const;
  public:
  void clear_asks();
  ::exchange::BookLevel* mutable_asks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >*
      mutable_asks();
  private:
  const ::exchange::BookLevel& _internal_asks(int index) const;
  ::exchange::BookLevel* _internal_add_asks();
  public:
  const ::exchange::BookLevel& asks(int index) const;
  ::exchange::BookLevel* add_asks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >&
      asks() const;

  // int64 timestamp_ns = 3;
  void clear_timestamp_ns();
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns() const;
  void set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_timestamp_ns() const;
  void _internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:exchange.BookSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel > bids_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel > asks_;
  ::PROTOBUF_NAMESPACE_ID::int64 timestamp_ns_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// -------------------------------------------------------------------

class Empty PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:exchange.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {};
  virtual ~Empty();

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Empty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Empty* New() const final {
    return CreateMaybeMessage<Empty>(nullptr);
  }

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "exchange.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_exchange_2eproto);
    return ::descriptor_table_exchange_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:exchange.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_exchange_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OrderRequest

// string order_id = 1;
inline void OrderRequest::clear_order_id() {
  order_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OrderRequest::order_id() const {
  // @@protoc_insertion_point(field_get:exchange.OrderRequest.order_id)
  return _internal_order_id();
}
inline void OrderRequest::set_order_id(const std::string& value) {
  _internal_set_order_id(value);
  // @@protoc_insertion_point(field_set:exchange.OrderRequest.order_id)
}
inline std::string* OrderRequest::mutable_order_id() {
  // @@protoc_insertion_point(field_mutable:exchange.OrderRequest.order_id)
  return _internal_mutable_order_id();
}
inline const std::string& OrderRequest::_internal_order_id() const {
  return order_id_.Get();
}
inline void OrderRequest::_internal_set_order_id(const std::string& value) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OrderRequest::set_order_id(std::string&& value) {
  
  order_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.OrderRequest.order_id)
}
inline void OrderRequest::set_order_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.OrderRequest.order_id)
}
inline void OrderRequest::set_order_id(const char* value,
    size_t size) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.OrderRequest.order_id)
}
inline std::string* OrderRequest::_internal_mutable_order_id() {
  
  return order_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OrderRequest::release_order_id() {
  // @@protoc_insertion_point(field_release:exchange.OrderRequest.order_id)
  return order_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OrderRequest::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), order_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.OrderRequest.order_id)
}
inline std::string* OrderRequest::unsafe_arena_release_order_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.OrderRequest.order_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return order_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OrderRequest::unsafe_arena_set_allocated_order_id(
    std::string* order_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      order_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.OrderRequest.order_id)
}

// .exchange.Side side = 2;
inline void OrderRequest::clear_side() {
  side_ = 0;
}
inline ::exchange::Side OrderRequest::_internal_side() const {
  return static_cast< ::exchange::Side >(side_);
}
inline ::exchange::Side OrderRequest::side() const {
  // @@protoc_insertion_point(field_get:exchange.OrderRequest.side)
  return _internal_side();
}
inline void OrderRequest::_internal_set_side(::exchange::Side value) {
  
  side_ = value;
}
inline void OrderRequest::set_side(::exchange::Side value) {
  _internal_set_side(value);
  // @@protoc_insertion_point(field_set:exchange.OrderRequest.side)
}

// double price = 3;
inline void OrderRequest::clear_price() {
  price_ = 0;
}
inline double OrderRequest::_internal_price() const {
  return price_;
}
inline double OrderRequest::price() const {
  // @@protoc_insertion_point(field_get:exchange.OrderRequest.price)
  return _internal_price();
}
inline void OrderRequest::_internal_set_price(double value) {
  
  price_ = value;
}
inline void OrderRequest::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:exchange.OrderRequest.price)
}

// int64 quantity = 4;
inline void OrderRequest::clear_quantity() {
  quantity_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 OrderRequest::_internal_quantity() const {
  return quantity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 OrderRequest::quantity() const {
  // @@protoc_insertion_point(field_get:exchange.OrderRequest.quantity)
  return _internal_quantity();
}
inline void OrderRequest::_internal_set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  quantity_ = value;
}
inline void OrderRequest::set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:exchange.OrderRequest.quantity)
}

// int64 timestamp_ns = 5;
inline void OrderRequest::clear_timestamp_ns() {
  timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 OrderRequest::_internal_timestamp_ns() const {
  return timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 OrderRequest::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:exchange.OrderRequest.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void OrderRequest::_internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ns_ = value;
}
inline void OrderRequest::set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:exchange.OrderRequest.timestamp_ns)
}

// -------------------------------------------------------------------

// OrderResponse

// string order_id = 1;
inline void OrderResponse::clear_order_id() {
  order_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OrderResponse::order_id() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.order_id)
  return _internal_order_id();
}
inline void OrderResponse::set_order_id(const std::string& value) {
  _internal_set_order_id(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.order_id)
}
inline std::string* OrderResponse::mutable_order_id() {
  // @@protoc_insertion_point(field_mutable:exchange.OrderResponse.order_id)
  return _internal_mutable_order_id();
}
inline const std::string& OrderResponse::_internal_order_id() const {
  return order_id_.Get();
}
inline void OrderResponse::_internal_set_order_id(const std::string& value) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OrderResponse::set_order_id(std::string&& value) {
  
  order_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.OrderResponse.order_id)
}
inline void OrderResponse::set_order_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.OrderResponse.order_id)
}
inline void OrderResponse::set_order_id(const char* value,
    size_t size) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.OrderResponse.order_id)
}
inline std::string* OrderResponse::_internal_mutable_order_id() {
  
  return order_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OrderResponse::release_order_id() {
  // @@protoc_insertion_point(field_release:exchange.OrderResponse.order_id)
  return order_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OrderResponse::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), order_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.OrderResponse.order_id)
}
inline std::string* OrderResponse::unsafe_arena_release_order_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.OrderResponse.order_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return order_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OrderResponse::unsafe_arena_set_allocated_order_id(
    std::string* order_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      order_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.OrderResponse.order_id)
}

// bool accepted = 2;
inline void OrderResponse::clear_accepted() {
  accepted_ = false;
}
inline bool OrderResponse::_internal_accepted() const {
  return accepted_;
}
inline bool OrderResponse::accepted() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.accepted)
  return _internal_accepted();
}
inline void OrderResponse::_internal_set_accepted(bool value) {
  
  accepted_ = value;
}
inline void OrderResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.accepted)
}

// string message = 3;
inline void OrderResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& OrderResponse::message() const {
  // @@protoc_insertion_point(field_get:exchange.OrderResponse.message)
  return _internal_message();
}
inline void OrderResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:exchange.OrderResponse.message)
}
inline std::string* OrderResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:exchange.OrderResponse.message)
  return _internal_mutable_message();
}
inline const std::string& OrderResponse::_internal_message() const {
  return message_.Get();
}
inline void OrderResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void OrderResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.OrderResponse.message)
}
inline void OrderResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.OrderResponse.message)
}
inline void OrderResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.OrderResponse.message)
}
inline std::string* OrderResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* OrderResponse::release_message() {
  // @@protoc_insertion_point(field_release:exchange.OrderResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void OrderResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.OrderResponse.message)
}
inline std::string* OrderResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.OrderResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void OrderResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.OrderResponse.message)
}

// -------------------------------------------------------------------

// CancelRequest

// string order_id = 1;
inline void CancelRequest::clear_order_id() {
  order_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CancelRequest::order_id() const {
  // @@protoc_insertion_point(field_get:exchange.CancelRequest.order_id)
  return _internal_order_id();
}
inline void CancelRequest::set_order_id(const std::string& value) {
  _internal_set_order_id(value);
  // @@protoc_insertion_point(field_set:exchange.CancelRequest.order_id)
}
inline std::string* CancelRequest::mutable_order_id() {
  // @@protoc_insertion_point(field_mutable:exchange.CancelRequest.order_id)
  return _internal_mutable_order_id();
}
inline const std::string& CancelRequest::_internal_order_id() const {
  return order_id_.Get();
}
inline void CancelRequest::_internal_set_order_id(const std::string& value) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CancelRequest::set_order_id(std::string&& value) {
  
  order_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.CancelRequest.order_id)
}
inline void CancelRequest::set_order_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.CancelRequest.order_id)
}
inline void CancelRequest::set_order_id(const char* value,
    size_t size) {
  
  order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.CancelRequest.order_id)
}
inline std::string* CancelRequest::_internal_mutable_order_id() {
  
  return order_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CancelRequest::release_order_id() {
  // @@protoc_insertion_point(field_release:exchange.CancelRequest.order_id)
  return order_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CancelRequest::set_allocated_order_id(std::string* order_id) {
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), order_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.CancelRequest.order_id)
}
inline std::string* CancelRequest::unsafe_arena_release_order_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.CancelRequest.order_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return order_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CancelRequest::unsafe_arena_set_allocated_order_id(
    std::string* order_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (order_id != nullptr) {
    
  } else {
    
  }
  order_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      order_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.CancelRequest.order_id)
}

// -------------------------------------------------------------------

// CancelResponse

// bool success = 1;
inline void CancelResponse::clear_success() {
  success_ = false;
}
inline bool CancelResponse::_internal_success() const {
  return success_;
}
inline bool CancelResponse::success() const {
  // @@protoc_insertion_point(field_get:exchange.CancelResponse.success)
  return _internal_success();
}
inline void CancelResponse::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void CancelResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:exchange.CancelResponse.success)
}

// -------------------------------------------------------------------

// Trade

// string trade_id = 1;
inline void Trade::clear_trade_id() {
  trade_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Trade::trade_id() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.trade_id)
  return _internal_trade_id();
}
inline void Trade::set_trade_id(const std::string& value) {
  _internal_set_trade_id(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.trade_id)
}
inline std::string* Trade::mutable_trade_id() {
  // @@protoc_insertion_point(field_mutable:exchange.Trade.trade_id)
  return _internal_mutable_trade_id();
}
inline const std::string& Trade::_internal_trade_id() const {
  return trade_id_.Get();
}
inline void Trade::_internal_set_trade_id(const std::string& value) {
  
  trade_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Trade::set_trade_id(std::string&& value) {
  
  trade_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.Trade.trade_id)
}
inline void Trade::set_trade_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trade_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.Trade.trade_id)
}
inline void Trade::set_trade_id(const char* value,
    size_t size) {
  
  trade_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.Trade.trade_id)
}
inline std::string* Trade::_internal_mutable_trade_id() {
  
  return trade_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Trade::release_trade_id() {
  // @@protoc_insertion_point(field_release:exchange.Trade.trade_id)
  return trade_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Trade::set_allocated_trade_id(std::string* trade_id) {
  if (trade_id != nullptr) {
    
  } else {
    
  }
  trade_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trade_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.Trade.trade_id)
}
inline std::string* Trade::unsafe_arena_release_trade_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.Trade.trade_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return trade_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Trade::unsafe_arena_set_allocated_trade_id(
    std::string* trade_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (trade_id != nullptr) {
    
  } else {
    
  }
  trade_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      trade_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.Trade.trade_id)
}

// string buy_order_id = 2;
inline void Trade::clear_buy_order_id() {
  buy_order_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Trade::buy_order_id() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.buy_order_id)
  return _internal_buy_order_id();
}
inline void Trade::set_buy_order_id(const std::string& value) {
  _internal_set_buy_order_id(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.buy_order_id)
}
inline std::string* Trade::mutable_buy_order_id() {
  // @@protoc_insertion_point(field_mutable:exchange.Trade.buy_order_id)
  return _internal_mutable_buy_order_id();
}
inline const std::string& Trade::_internal_buy_order_id() const {
  return buy_order_id_.Get();
}
inline void Trade::_internal_set_buy_order_id(const std::string& value) {
  
  buy_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Trade::set_buy_order_id(std::string&& value) {
  
  buy_order_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.Trade.buy_order_id)
}
inline void Trade::set_buy_order_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  buy_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.Trade.buy_order_id)
}
inline void Trade::set_buy_order_id(const char* value,
    size_t size) {
  
  buy_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.Trade.buy_order_id)
}
inline std::string* Trade::_internal_mutable_buy_order_id() {
  
  return buy_order_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Trade::release_buy_order_id() {
  // @@protoc_insertion_point(field_release:exchange.Trade.buy_order_id)
  return buy_order_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Trade::set_allocated_buy_order_id(std::string* buy_order_id) {
  if (buy_order_id != nullptr) {
    
  } else {
    
  }
  buy_order_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), buy_order_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.Trade.buy_order_id)
}
inline std::string* Trade::unsafe_arena_release_buy_order_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.Trade.buy_order_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return buy_order_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Trade::unsafe_arena_set_allocated_buy_order_id(
    std::string* buy_order_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (buy_order_id != nullptr) {
    
  } else {
    
  }
  buy_order_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      buy_order_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.Trade.buy_order_id)
}

// string sell_order_id = 3;
inline void Trade::clear_sell_order_id() {
  sell_order_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Trade::sell_order_id() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.sell_order_id)
  return _internal_sell_order_id();
}
inline void Trade::set_sell_order_id(const std::string& value) {
  _internal_set_sell_order_id(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.sell_order_id)
}
inline std::string* Trade::mutable_sell_order_id() {
  // @@protoc_insertion_point(field_mutable:exchange.Trade.sell_order_id)
  return _internal_mutable_sell_order_id();
}
inline const std::string& Trade::_internal_sell_order_id() const {
  return sell_order_id_.Get();
}
inline void Trade::_internal_set_sell_order_id(const std::string& value) {
  
  sell_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Trade::set_sell_order_id(std::string&& value) {
  
  sell_order_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:exchange.Trade.sell_order_id)
}
inline void Trade::set_sell_order_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  sell_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:exchange.Trade.sell_order_id)
}
inline void Trade::set_sell_order_id(const char* value,
    size_t size) {
  
  sell_order_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:exchange.Trade.sell_order_id)
}
inline std::string* Trade::_internal_mutable_sell_order_id() {
  
  return sell_order_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Trade::release_sell_order_id() {
  // @@protoc_insertion_point(field_release:exchange.Trade.sell_order_id)
  return sell_order_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Trade::set_allocated_sell_order_id(std::string* sell_order_id) {
  if (sell_order_id != nullptr) {
    
  } else {
    
  }
  sell_order_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), sell_order_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:exchange.Trade.sell_order_id)
}
inline std::string* Trade::unsafe_arena_release_sell_order_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:exchange.Trade.sell_order_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return sell_order_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Trade::unsafe_arena_set_allocated_sell_order_id(
    std::string* sell_order_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (sell_order_id != nullptr) {
    
  } else {
    
  }
  sell_order_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      sell_order_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:exchange.Trade.sell_order_id)
}

// double price = 4;
inline void Trade::clear_price() {
  price_ = 0;
}
inline double Trade::_internal_price() const {
  return price_;
}
inline double Trade::price() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.price)
  return _internal_price();
}
inline void Trade::_internal_set_price(double value) {
  
  price_ = value;
}
inline void Trade::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.price)
}

// int64 quantity = 5;
inline void Trade::clear_quantity() {
  quantity_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Trade::_internal_quantity() const {
  return quantity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Trade::quantity() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.quantity)
  return _internal_quantity();
}
inline void Trade::_internal_set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  quantity_ = value;
}
inline void Trade::set_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_quantity(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.quantity)
}

// int64 timestamp_ns = 6;
inline void Trade::clear_timestamp_ns() {
  timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Trade::_internal_timestamp_ns() const {
  return timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 Trade::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:exchange.Trade.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void Trade::_internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ns_ = value;
}
inline void Trade::set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:exchange.Trade.timestamp_ns)
}

// -------------------------------------------------------------------

// BookLevel

// double price = 1;
inline void BookLevel::clear_price() {
  price_ = 0;
}
inline double BookLevel::_internal_price() const {
  return price_;
}
inline double BookLevel::price() const {
  // @@protoc_insertion_point(field_get:exchange.BookLevel.price)
  return _internal_price();
}
inline void BookLevel::_internal_set_price(double value) {
  
  price_ = value;
}
inline void BookLevel::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:exchange.BookLevel.price)
}

// int64 total_quantity = 2;
inline void BookLevel::clear_total_quantity() {
  total_quantity_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BookLevel::_internal_total_quantity() const {
  return total_quantity_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BookLevel::total_quantity() const {
  // @@protoc_insertion_point(field_get:exchange.BookLevel.total_quantity)
  return _internal_total_quantity();
}
inline void BookLevel::_internal_set_total_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  total_quantity_ = value;
}
inline void BookLevel::set_total_quantity(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_total_quantity(value);
  // @@protoc_insertion_point(field_set:exchange.BookLevel.total_quantity)
}

// -------------------------------------------------------------------

// BookSnapshot

// repeated .exchange.BookLevel bids = 1;
inline int BookSnapshot::_internal_bids_size() const {
  return bids_.size();
}
inline int BookSnapshot::bids_size() const {
  return _internal_bids_size();
}
inline void BookSnapshot::clear_bids() {
  bids_.Clear();
}
inline ::exchange::BookLevel* BookSnapshot::mutable_bids(int index) {
  // @@protoc_insertion_point(field_mutable:exchange.BookSnapshot.bids)
  return bids_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >*
BookSnapshot::mutable_bids() {
  // @@protoc_insertion_point(field_mutable_list:exchange.BookSnapshot.bids)
  return &bids_;
}
inline const ::exchange::BookLevel& BookSnapshot::_internal_bids(int index) const {
  return bids_.Get(index);
}
inline const ::exchange::BookLevel& BookSnapshot::bids(int index) const {
  // @@protoc_insertion_point(field_get:exchange.BookSnapshot.bids)
  return _internal_bids(index);
}
inline ::exchange::BookLevel* BookSnapshot::_internal_add_bids() {
  return bids_.Add();
}
inline ::exchange::BookLevel* BookSnapshot::add_bids() {
  // @@protoc_insertion_point(field_add:exchange.BookSnapshot.bids)
  return _internal_add_bids();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >&
BookSnapshot::bids() const {
  // @@protoc_insertion_point(field_list:exchange.BookSnapshot.bids)
  return bids_;
}

// repeated .exchange.BookLevel asks = 2;
inline int BookSnapshot::_internal_asks_size() const {
  return asks_.size();
}
inline int BookSnapshot::asks_size() const {
  return _internal_asks_size();
}
inline void BookSnapshot::clear_asks() {
  asks_.Clear();
}
inline ::exchange::BookLevel* BookSnapshot::mutable_asks(int index) {
  // @@protoc_insertion_point(field_mutable:exchange.BookSnapshot.asks)
  return asks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >*
BookSnapshot::mutable_asks() {
  // @@protoc_insertion_point(field_mutable_list:exchange.BookSnapshot.asks)
  return &asks_;
}
inline const ::exchange::BookLevel& BookSnapshot::_internal_asks(int index) const {
  return asks_.Get(index);
}
inline const ::exchange::BookLevel& BookSnapshot::asks(int index) const {
  // @@protoc_insertion_point(field_get:exchange.BookSnapshot.asks)
  return _internal_asks(index);
}
inline ::exchange::BookLevel* BookSnapshot::_internal_add_asks() {
  return asks_.Add();
}
inline ::exchange::BookLevel* BookSnapshot::add_asks() {
  // @@protoc_insertion_point(field_add:exchange.BookSnapshot.asks)
  return _internal_add_asks();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::exchange::BookLevel >&
BookSnapshot::asks() const {
  // @@protoc_insertion_point(field_list:exchange.BookSnapshot.asks)
  return asks_;
}

// int64 timestamp_ns = 3;
inline void BookSnapshot::clear_timestamp_ns() {
  timestamp_ns_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BookSnapshot::_internal_timestamp_ns() const {
  return timestamp_ns_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 BookSnapshot::timestamp_ns() const {
  // @@protoc_insertion_point(field_get:exchange.BookSnapshot.timestamp_ns)
  return _internal_timestamp_ns();
}
inline void BookSnapshot::_internal_set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  timestamp_ns_ = value;
}
inline void BookSnapshot::set_timestamp_ns(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_timestamp_ns(value);
  // @@protoc_insertion_point(field_set:exchange.BookSnapshot.timestamp_ns)
}

// -------------------------------------------------------------------

// Empty

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace exchange

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::exchange::Side> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::exchange::Side>() {
  return ::exchange::Side_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_exchange_2eproto
